<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-07-04 21:15
=======
# Generated by Django 5.0.6 on 2024-06-01 04:49
>>>>>>> parent of fc88f99 (Created Member model. Created MemberSignupForm. Implemented fully-functional Sign up, Login, and Logout views.)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_number', models.IntegerField(default='000000000', primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default='0000000000')),
                ('major', models.CharField(max_length=50)),
                ('linkedIn', models.URLField(default='http://www.linkedin.com', max_length=50)),
            ],
        ),
    ]
